name: Build and Publish
on:
  push:
    tags:
      - v*
permissions:
  contents: write
  id-token: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🍔🍟🥤
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Use Node.js 😂
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Test 🧪
        run: |
          npm ci
          npm run check-ci
          npm publish
